version: '3'

services:
  app:
    build: .
    volumes:
      - .:/var/www
    networks:
      - app-network
    expose:
      - 9000

  nginx:
    build: ./.docker/nginx
    volumes:
      - .:/var/www
    ports:
      - 8000:80
    networks:
      - app-network
    restart: always
    tty: true

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
