version: '3'

services:
  app:
    build: .
    tty: true
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/app/entrypoint.sh
    volumes:
      - .:/var/www
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network
    expose:
      - 9000

  db:
    build: ./.docker/mysql
    restart: always
    tty: true
    expose:
      - 3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYQSQL_USER=root
    networks:
      - app-network

  nginx:
    build: ./.docker/nginx
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.tmpl:/etc/nginx/conf.d/nginx.conf nginx -g 'daemon off';
    volumes:
      - .:/var/www/
    tty: true
    environment:
      - PROXY_URL=app:9000
    ports:
      - 8000:80
    networks:
      - app-network

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
